<?php

return [
    [
        'name'                  => 'فارسی',
        'code'                  => 'fa',
        'direction'             => 'RTL',
        'status'                => 'ACTIVE',
        'state'                 => 'DEFAULT',
        'timezones'             =>  [
            'Asia/Tehran',
        ],
    ],
    [
        'name'                  => 'English',
        'code'                  => 'en',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'America/New_York',
            'America/Detroit',
            'America/Kentucky/Louisville',
            'America/Kentucky/Monticello',
            'America/Indiana/Indianapolis',
            'America/Indiana/Vincennes',
            'America/Indiana/Winamac',
            'America/Indiana/Marengo',
            'America/Indiana/Petersburg',
            'America/Indiana/Vevay',
            'America/Chicago',
            'America/Indiana/Tell_City',
            'America/Indiana/Knox',
            'America/Menominee',
            'America/North_Dakota/Center',
            'America/North_Dakota/New_Salem',
            'America/North_Dakota/Beulah',
            'America/Denver',
            'America/Boise',
            'America/Phoenix',
            'America/Los_Angeles',
            'America/Anchorage',
            'America/Juneau',
            'America/Sitka',
            'America/Metlakatla',
            'America/Yakutat',
            'America/Nome',
            'America/Adak',
            'Pacific/Honolulu',
            'Europe/London',
            'Pacific/Auckland',
            'Antarctica/Macquarie',
            'Australia/Adelaide',
            'Australia/Brisbane',
            'Australia/Broken_Hill',
            'Australia/Currie',
            'Australia/Darwin',
            'Australia/Eucla',
            'Australia/Hobart',
            'Australia/Lindeman',
            'Australia/Lord_Howe',
            'Australia/Melbourne',
            'Australia/Perth',
            'Australia/Sydney',
            'America/Antigua',
            'America/Nassau',
            'America/Barbados',
            'America/Belize',
            'Africa/Gaborone',
            'Africa/Bujumbura',
            'Africa/Douala',
            'America/Atikokan',
            'America/Blanc-Sablon',
            'America/Cambridge_Bay',
            'America/Creston',
            'America/Dawson',
            'America/Dawson_Creek',
            'America/Edmonton',
            'America/Fort_Nelson',
            'America/Glace_Bay',
            'America/Goose_Bay',
            'America/Halifax',
            'America/Inuvik',
            'America/Iqaluit',
            'America/Moncton',
            'America/Nipigon',
            'America/Pangnirtung',
            'America/Rainy_River',
            'America/Rankin_Inlet',
            'America/Regina',
            'America/Resolute',
            'America/St_Johns',
            'America/Swift_Current',
            'America/Thunder_Bay',
            'America/Toronto',
            'America/Vancouver',
            'America/Whitehorse',
            'America/Winnipeg',
            'America/Yellowknife',
            'America/Dominica',
            'Pacific/Fiji',
            'Africa/Banjul',
            'Africa/Accra',
            'America/Grenada',
            'America/Guyana',
            'Europe/Dublin',
            'America/Jamaica',
            'Africa/Nairobi',
            'Africa/Monrovia',
            'Africa/Blantyre',
            'Indian/Mauritius',
            'Pacific/Chuuk',
            'Pacific/Pohnpei',
            'Pacific/Kosrae',
            'Africa/Lagos',
            'Pacific/Port_Moresby',
            'America/St_Kitts',
            'America/St_Lucia',
            'America/St_Vincent',
            'Africa/Freetown',
            'Asia/Singapore',
            'Pacific/Guadalcanal',
            'Africa/Johannesburg',
            'Africa/Juba',
            'America/Port_of_Spain',
            'Africa/Lusaka',
        ]
    ],
    [
        'name'                  => 'العربية',
        'code'                  => 'ar',
        'direction'             => 'RTL',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Africa/Algiers',
            'Asia/Bahrain',
            'Indian/Comoro',
            'Africa/Djibouti',
            'Africa/Cairo',
            'Asia/Baghdad',
            'Asia/Amman',
            'Asia/Kuwait',
            'Asia/Beirut',
            'Africa/Tripoli',
            'Africa/Nouakchott',
            'Africa/Casablanca',
            'Africa/El_Aaiun',
            'Asia/Muscat',
            'Asia/Gaza',
            'Asia/Hebron',
            'Asia/Qatar',
            'Asia/Riyadh',
            'Africa/Mogadishu',
            'Africa/Khartoum',
            'Asia/Damascus',
            'Africa/Tunis',
            'Asia/Dubai',
            'Asia/Aden',
        ]
    ],
    [
        'name'                  => 'Chinese',
        'code'                  => 'zh',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             =>  [
            'Asia/Shanghai',
            'Asia/Taipei',
            'Asia/Hong_Kong',
        ],
    ],
    [
        'name'                  => 'Spanish',
        'code'                  => 'es',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'America/Mexico_City',
            'America/Cancun',
            'America/Merida',
            'America/Monterrey',
            'America/Matamoros',
            'America/Mazatlan',
            'America/Chihuahua',
            'America/Ojinaga',
            'America/Hermosillo',
            'America/Tijuana',
            'America/Bahia_Banderas',
            'America/Bogota',
            'Europe/Madrid',
            'America/Argentina/Buenos_Aires',
            'America/Argentina/Catamarca',
            'America/Argentina/Cordoba',
            'America/Argentina/Jujuy',
            'America/Argentina/La_Rioja',
            'America/Argentina/Mendoza',
            'America/Argentina/Rio_Gallegos',
            'America/Argentina/Salta',
            'America/Argentina/San_Juan',
            'America/Argentina/San_Luis',
            'America/Argentina/Tucuman',
            'America/Argentina/Ushuaia',
            'America/Lima',
            'America/Caracas',
            'America/Santiago',
            'America/Guatemala',
            'Pacific/Galapagos',
            'America/La_Paz',
            'America/Havana',
            'America/Santo_Domingo',
            'America/Tegucigalpa',
            'America/Asuncion',
            'America/El_Salvador',
            'America/Managua',
            'America/Costa_Rica',
            'America/Panama',
            'America/Montevideo',
            'Africa/Malabo',
        ]
    ],
    [
        'name'                  => 'Hindi',
        'code'                  => 'hi',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Asia/Karachi',
            'Asia/Kolkata',
        ]
    ],
    [
        'name'                  => 'Portuguese',
        'code'                  => 'pt',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Africa/Luanda',
            'America/Araguaina',
            'America/Bahia',
            'America/Belem',
            'America/Boa_Vista',
            'America/Campo_Grande',
            'America/Cuiaba',
            'America/Eirunepe',
            'America/Fortaleza',
            'America/Maceio',
            'America/Manaus',
            'America/Noronha',
            'America/Porto_Velho',
            'America/Recife',
            'America/Rio_Branco',
            'America/Santarem',
            'America/Sao_Paulo',
            'Asia/Dili',
            'Africa/Malabo',
            'Africa/Bissau',
            'Africa/Maputo',
            'Europe/Lisbon',
            'Africa/Sao_Tome',
        ]
    ],
    [
        'name'                  => 'Bengali',
        'code'                  => 'bn',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Asia/Dhaka',
            'Asia/Thimphu',
        ]
    ],
    [
        'name'                  => 'Russian',
        'code'                  => 'ru',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Europe/Moscow',
            'Europe/Simferopol',
            'Europe/Kaliningrad',
            'Europe/Volgograd',
            'Europe/Samara',
            'Asia/Yekaterinburg',
            'Asia/Omsk',
            'Asia/Novosibirsk',
            'Asia/Krasnoyarsk',
            'Asia/Irkutsk',
            'Asia/Yakutsk',
            'Asia/Vladivostok',
            'Asia/Sakhalin',
            'Asia/Magadan',
            'Asia/Kamchatka',
            'Asia/Anadyr',
            'Europe/Minsk',
            'Asia/Almaty',
            'Asia/Qyzylorda',
            'Asia/Aqtobe',
            'Asia/Aqtau',
            'Asia/Oral',
            'Asia/Bishkek',
            'Asia/Dushanbe',
        ]
    ],
    [
        'name'                  => 'Japanese',
        'code'                  => 'ja',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Asia/Tokyo',
        ]
    ],
    [
        'name'                  => 'Vietnamese',
        'code'                  => 'vi',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Asia/Ho_Chi_Minh',
        ]
    ],
    [
        'name'                  => 'Turkish',
        'code'                  => 'tr',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Europe/Istanbul',
            'Asia/Baku',
        ]
    ],
    [
        'name'                  => 'Korean',
        'code'                  => 'ko',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Asia/Seoul',
            'Asia/Pyongyang',
        ]
    ],
    [
        'name'                  => 'French',
        'code'                  => 'fr',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Africa/Porto-Novo',
            'Africa/Ouagadougou',
            'Africa/Brazzaville',
            'Europe/Paris',
            'Africa/Libreville',
            'Africa/Conakry',
            'Europe/Monaco',
            'Africa/Dakar',
            'Africa/Lome',
        ]
    ],
    [
        'name'                  => 'German',
        'code'                  => 'de',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Europe/Berlin',
            'Europe/Brussels',
            'Europe/Vienna',
            'Europe/Zurich',
            'Europe/Luxembourg',
            'Europe/Vaduz',
        ]
    ],
    [
        'name'                  => 'Italian',
        'code'                  => 'it',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             => [
            'Europe/Zurich',
            'Europe/Rome',
            'Europe/San_Marino',
            'Europe/Vatican',
        ]
    ],
    [
        'name'                  => 'Kurmanji Kurdish',
        'code'                  => 'ku',
        'direction'             => 'LTR',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             =>  [
            'Europe/Istanbul',
            'Asia/Damascus',
            'Asia/Baghdad',
            'Asia/Tehran',
        ],
    ],
    [
        'name'                  => 'Sorani Kurdish',
        'code'                  => 'ku-so',
        'direction'             => 'RTL',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             =>  [
            'Asia/Baghdad',
            'Asia/Tehran',
        ],
    ],
    [
        'name'                  => 'Southern Kurdish',
        'code'                  => 'ku-su',
        'direction'             => 'RTL',
        'status'                => 'INACTIVE',
        'state'                 => 'NON_DEFAULT',
        'timezones'             =>  [
            'Asia/Baghdad',
            'Asia/Tehran',
        ],
    ],
];
