<?php

namespace Fooino\Core\Tasks;

use Fooino\Core\Support\SingletonableTask;

class GetForbiddenFilesTask extends SingletonableTask
{
    /**
     * Build the forbidden file name and extension list, ordered by length so longer entries like '.php-cs-fixer.php' match before their shorter parts
     */
    protected function getData(): mixed
    {
        $files = [
            'oauth-private.key',
            'oauth-public.key',
            'package-lock.json',
            'package.json',
            'composer.json',
            'composer.lock',
            '.gitlab-ci.yml',
            '.gitlab-ci.yaml',
            '.env.example',
            '.env.testing',
            '.env.local',
            '.env.production',
            '.env.staging',
            '.env.development',
            '.env.encrypted',
            '.env.decrypted',
            '.env.old',
            '.env.backup',
            '.env',
            'index.php',
            'supervisor.log',
            'phpunit.xml',
            'error_log',
            '.gitignore',
            '.gitkeep',
            'laravel.logs',
            'laravel.log',
            'api-docs.json',
            '.editorconfig',
            '.htaccess',
            '.htpasswd',
            '.key',
            '.pem',
            '.crt',
            '.logs',
            '.log',
            '.php',
            '.phtml',
            '.phar',
            '.pht',
            '.php3',
            '.php4',
            '.php5',
            '.php7',
            '.php8',
            '.shtml',
            '.shtm',
            '.git',
            '.sql',
            '.sqlite',
            '.json',
            '.zip',
            '.rar',
            '.js',
            '.css',
            '.html',
            '.xml',
            '.yml',
            '.yaml',
            '.md',
            '.blade',
            '.stub',
            '.bak',
            '.swp',
            '.swo',
            '.old',
            '.orig',
            '.py',
            '.pyc',
            '.bat',
            '.bash',
            '.sh',
            '.exe',
            '.cmd',
            '.asp',
            '.aspx',
            '.jsp',
            '.cgi',
            '.pl',
            '.rb',
            'artisan',
            'Dockerfile',
            'Makefile',
            'Procfile',
            'docker-compose.yml',
            'docker-compose.yaml',
            'next.config.js',
            'next.config.ts',
            'nginx.conf',
            'phpstan.neon',
            'phpstan.neon.dist',
            'phpunit.xml.dist',
            'tailwind.config.js',
            'tailwind.config.ts',
            'vite.config.js',
            'vite.config.ts',
            'yarn.lock',
            '.dockerignore',
            '.gitattributes',
            '.npmrc',
            '.php-cs-fixer.php',
            '.php-cs-fixer.dist.php',
            'makefile'
        ];

        usort($files, fn(mixed $a, mixed $b) => strlen($b) <=> strlen($a));

        return $files;
    }
}
